
enum Keys
{
  CURRENT_SCREEN_KEY = 0,
  CURRENT_MENU_KEY = 1,
  SERVER_ERROR_KEY = 2,
  LOCATION_STATUS_KEY = 3,
	
  BOAT_LAT_KEY = 101,
  BOAT_LON_KEY = 102,
  BOAT_SOG_KEY = 103,
  BOAT_COG_KEY = 104,
  BOAT_BOAT_SPEED_KEY = 105,
  BOAT_DEPTH_KEY = 106,
  BOAT_WIND_SPEED_KEY = 107,
  BOAT_WIND_ANGLE_KEY = 108,
  BOAT_DTW_KEY = 109,
  BOAT_BTW_KEY = 110,
  BOAT_WAYPOINT_KEY = 111,
  BOAT_WPT_LAT_KEY = 112,
  BOAT_WPT_LON_KEY = 113,
  BOAT_TEMP_KEY = 114,
  BOAT_DISTANCE_TOTAL_KEY = 115,
  BOAT_DISTANCE_RESET_KEY = 116,
  BOAT_DRIFT_KEY = 117,
	  
  SET_ANCHOR_WATCH_KEY = 202,
};
extern enum Keys keys;